# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3
      - name: Install dependencies
        run: |
          poetry install
      - name: Test with pytest and coverage
        run: |
          pytest --cov=./vanilla_option_pricing --cov-report=xml
      - name: Upload coverage stats
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
